// ------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本: 11.0.0.0
//  
//     对此文件的更改可能会导致不正确的行为。此外，如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MyCodeAddin.EditRead
{
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "11.0.0.0")]
    public partial class EditReadObjectFactory : EditReadObjectFactoryBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("using System;\r\nusing System.Collections.Generic;\r\nusing System.Linq;\r\nusing Syste" +
                    "m.Text;\r\nusing EF;\r\nusing EF.Data;\r\nusing EF.Linq;\r\nusing EF.Server;\r\nusing EFra" +
                    "mework.DalLinq;\r\n\r\nnamespace ");
            
            #line 12 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DalNameSpace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n\tpublic class ");
            
            #line 14 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("Factory:");
            
            #line 14 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(BusNameSpace));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 14 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("\r\n    {\r\n        public static ");
            
            #line 16 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(BusNameSpace));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 16 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(" Fetch(");
            
            #line 16 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write(" data)\r\n        {\r\n            ");
            
            #line 18 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(BusNameSpace));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 18 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(" item = (");
            
            #line 18 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(BusNameSpace));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 18 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(")Activator.CreateInstance(typeof(");
            
            #line 18 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(BusNameSpace));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 18 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("));\r\n            using (ObjectFactory.BypassPropertyChecks(item))\r\n            {\r" +
                    "\n\t\t\t\t");
            
            #line 21 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
foreach(var item in Items)
				{
            
            #line default
            #line hidden
            this.Write("                item.");
            
            #line 23 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" = data.");
            
            #line 23 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t\t");
            
            #line 24 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
}
            
            #line default
            #line hidden
            this.Write("\t\t\t}\r\n\t\t\tObjectFactory.MarkAsChild(item);\r\n            ObjectFactory.MarkOld(item" +
                    ");\r\n            return item;\r\n        }\r\n\r\n\t\tprivate void DataPortal_Fetch(");
            
            #line 31 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(BusNameSpace));
            
            #line default
            #line hidden
            this.Write(".LambdaExpression lambda)\r\n        {\r\n            using (var ctx = ContextManager" +
                    "<EFDataContext>.GetManager(Database.EFramework))\r\n            {\r\n\t\t\t\tvar exp = l" +
                    "ambda.Resolve<");
            
            #line 35 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write(">();\r\n                var i = (from p in ctx.DataContext.");
            
            #line 36 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write(".Where(exp)\r\n                         select p).SingleOrDefault();\r\n             " +
                    "   if (i != null)\r\n                {\r\n\t\t\t\t\t");
            
            #line 40 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
foreach(var item in Items)
					{
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\tthis.");
            
            #line 42 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" = i.");
            
            #line 42 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t\t\t");
            
            #line 43 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
}
            
            #line default
            #line hidden
            this.Write(@"}
            }
        }

		[Transactional(TransactionalTypes.TransactionScope)]
        protected override void DataPortal_Insert()
        {
            using (var ctx = ContextManager<EFDataContext>.GetManager(Database.EFramework))
            {
                ");
            
            #line 52 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(BusNameSpace));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 52 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(" data = this;\r\n                ctx.DataContext.Insert<");
            
            #line 53 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write(">(p => new ");
            
            #line 53 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write(" {\r\n\t\t\t\t\t\t");
            
            #line 54 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
 foreach(var item in Items)
						{  if(item.Name=="ChangedUser"){
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t");
            
            #line 56 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("=ApplicationContext.User.Identity.Name,\r\n\t\t\t\t\t\t");
            
            #line 57 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
;}else if(item.Name=="CreatedUser"){
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t");
            
            #line 58 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("=ApplicationContext.User.Identity.Name,\r\n\t\t\t\t\t\t");
            
            #line 59 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
;}else if(item.Name=="ChangedDate"){
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t");
            
            #line 60 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("=System.DateTime.Now,\r\n\t\t\t\t\t\t");
            
            #line 61 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
;}else if(item.Name=="CreatedDate"){
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t");
            
            #line 62 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("=System.DateTime.Now,\r\n\t\t\t\t\t\t");
            
            #line 63 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
;}else {
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t");
            
            #line 64 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" = data.");
            
            #line 64 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(",\r\n\t\t\t\t\t\t");
            
            #line 65 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
;}}
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t});\r\n\t\t\t\tEF.Log.Logger.Trace(EF.Log.TraceLevel.Info, string.Format(\"插入了表");
            
            #line 67 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write("的数据");
            
            #line 67 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
for(int i=0;i<KeyItems.Count;i++){
            
            #line default
            #line hidden
            
            #line 67 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(KeyItems[i].Name));
            
            #line default
            #line hidden
            this.Write("={");
            
            #line 67 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write("};");
            
            #line 67 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
;}
            
            #line default
            #line hidden
            this.Write("\"");
            
            #line 67 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
for(int i=0;i<KeyItems.Count;i++){
            
            #line default
            #line hidden
            this.Write(",data.");
            
            #line 67 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(KeyItems[i].Name));
            
            #line default
            #line hidden
            
            #line 67 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
;}
            
            #line default
            #line hidden
            this.Write(@"));
            }
            
        }

		[Transactional(TransactionalTypes.TransactionScope)]
        private void Chlid_Insert()
        {
			 using (var ctx = ContextManager<EFDataContext>.GetManager(Database.EFramework))
            {
                ");
            
            #line 77 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(BusNameSpace));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 77 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(" data = this;\r\n                ctx.DataContext.Insert<");
            
            #line 78 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write(">(p => new ");
            
            #line 78 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write(" {\r\n\t\t\t\t\t\t");
            
            #line 79 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
 foreach(var item in Items)
						{  if(item.Name=="ChangedUser"){
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t");
            
            #line 81 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("=ApplicationContext.User.Identity.Name,\r\n\t\t\t\t\t\t");
            
            #line 82 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
;}else if(item.Name=="CreatedUser"){
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t");
            
            #line 83 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("=ApplicationContext.User.Identity.Name,\r\n\t\t\t\t\t\t");
            
            #line 84 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
;}else if(item.Name=="ChangedDate"){
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t");
            
            #line 85 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("=System.DateTime.Now,\r\n\t\t\t\t\t\t");
            
            #line 86 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
;}else if(item.Name=="CreatedDate"){
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t");
            
            #line 87 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("=System.DateTime.Now,\r\n\t\t\t\t\t\t");
            
            #line 88 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
;}else {
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t");
            
            #line 89 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" = data.");
            
            #line 89 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(",\r\n\t\t\t\t\t\t");
            
            #line 90 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
;}}
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t});\r\n\t\t\t\tEF.Log.Logger.Trace(EF.Log.TraceLevel.Info, string.Format(\"插入了表");
            
            #line 92 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write("的数据");
            
            #line 92 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
for(int i=0;i<KeyItems.Count;i++){
            
            #line default
            #line hidden
            
            #line 92 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(KeyItems[i].Name));
            
            #line default
            #line hidden
            this.Write("={");
            
            #line 92 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write("};");
            
            #line 92 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
;}
            
            #line default
            #line hidden
            this.Write("\"");
            
            #line 92 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
for(int i=0;i<KeyItems.Count;i++){
            
            #line default
            #line hidden
            this.Write(",data.");
            
            #line 92 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(KeyItems[i].Name));
            
            #line default
            #line hidden
            
            #line 92 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
;}
            
            #line default
            #line hidden
            this.Write("));\r\n            }\r\n\t\t}\r\n\r\n\t\t");
            
            #line 96 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
 if(KeyItems.Count==1)
		{ 
		
            
            #line default
            #line hidden
            this.Write("\r\n\t\tprivate void DataPortal_Fetch(string code)\r\n        {\r\n            using (var" +
                    " ctx = ContextManager<EFDataContext>.GetManager(Database.EFramework))\r\n         " +
                    "   {\r\n                var i = (from p in ctx.DataContext.");
            
            #line 104 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write("\r\n                         where  p.");
            
            #line 105 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(KeyItems[0].Name));
            
            #line default
            #line hidden
            this.Write("==code\r\n                         select p).SingleOrDefault();\r\n                if" +
                    " (i != null)\r\n                {\r\n\t\t\t\t\t");
            
            #line 109 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
foreach(var item in Items)
					{
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\tthis.");
            
            #line 111 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" = i.");
            
            #line 111 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t\t  ");
            
            #line 112 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
}
            
            #line default
            #line hidden
            this.Write(@"				}
            }
        }

		[Transactional(TransactionalTypes.TransactionScope)]
        private void DataPortal_Delete(string code)
        {
            using (var ctx = ContextManager<EFDataContext>.GetManager(Database.EFramework))
            {
                using (BypassPropertyChecks)
                {
                    ctx.DataContext.DeleteByPK<");
            
            #line 124 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write(">(code);\r\n                }\r\n\t\t\t\tEF.Log.Logger.Trace(EF.Log.TraceLevel.Info, stri" +
                    "ng.Format(\"删除了表");
            
            #line 126 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write(@"的数据{0}"",code));
            }
        }

		[Transactional(TransactionalTypes.TransactionScope)]
        private void Child_DeleteSelf()
        {
            using (var ctx = ContextManager<EFDataContext>.GetManager(Database.EFramework))
            {
                using (BypassPropertyChecks)
                {
                    ctx.DataContext.DeleteByPK<");
            
            #line 137 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write(">(this.");
            
            #line 137 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(KeyItems[0].Name));
            
            #line default
            #line hidden
            this.Write(");\r\n                }\r\n            }\r\n            EF.Log.Logger.Trace(EF.Log.Trac" +
                    "eLevel.Info, string.Format(\"删除了表");
            
            #line 140 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write("的数据{0}\",this.");
            
            #line 140 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(KeyItems[0].Name));
            
            #line default
            #line hidden
            this.Write(@"));
        }

		[Transactional(TransactionalTypes.TransactionScope)]
        protected override void DataPortal_Update()
        {
            using (var ctx = ContextManager<EFDataContext>.GetManager(Database.EFramework))
            {
                ");
            
            #line 148 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(BusNameSpace));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 148 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(" data = this;\r\n                ctx.DataContext.UpdateByPK<");
            
            #line 149 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write(">(p => new ");
            
            #line 149 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write("\r\n                {\r\n\t\t\t\t\t\t");
            
            #line 151 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
 foreach(var item in NoKeyItems){  if(item.Name=="ChangedUser"){
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t");
            
            #line 152 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("=ApplicationContext.User.Identity.Name,\r\n\t\t\t\t\t\t");
            
            #line 153 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
;}else if(item.Name=="CreatedUser"){
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t");
            
            #line 154 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
;}else if(item.Name=="ChangedDate"){
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t");
            
            #line 155 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("=System.DateTime.Now,\r\n\t\t\t\t\t\t");
            
            #line 156 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
;}else if(item.Name=="CreatedDate"){
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t");
            
            #line 157 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
;}else {
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t");
            
            #line 158 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" = data.");
            
            #line 158 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(",\r\n\t\t\t\t\t\t");
            
            #line 159 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
;}}
            
            #line default
            #line hidden
            this.Write("\t\t\t\t},\r\n                data.");
            
            #line 161 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(KeyItems[0].Name));
            
            #line default
            #line hidden
            this.Write("\r\n                );\r\n\t\t\t\tEF.Log.Logger.Trace(EF.Log.TraceLevel.Info, string.Form" +
                    "at(\"更新了表");
            
            #line 163 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write("的数据{0}\",data.");
            
            #line 163 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(KeyItems[0].Name));
            
            #line default
            #line hidden
            this.Write("));\r\n            }\r\n        }\r\n\r\n\t\t[Transactional(TransactionalTypes.TransactionS" +
                    "cope)]\r\n        private void Child_Update()\r\n        {\r\n\t\t\tusing (var ctx = Cont" +
                    "extManager<EFDataContext>.GetManager(Database.EFramework))\r\n            {\r\n     " +
                    "           ");
            
            #line 172 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(BusNameSpace));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 172 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(" data = this;\r\n                ctx.DataContext.UpdateByPK<");
            
            #line 173 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write(">(p => new ");
            
            #line 173 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write("\r\n                {\r\n\t\t\t\t\t\t");
            
            #line 175 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
 foreach(var item in NoKeyItems){  if(item.Name=="ChangedUser"){
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t");
            
            #line 176 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("=ApplicationContext.User.Identity.Name,\r\n\t\t\t\t\t\t");
            
            #line 177 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
;}else if(item.Name=="CreatedUser"){
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t");
            
            #line 178 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
;}else if(item.Name=="ChangedDate"){
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t");
            
            #line 179 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("=System.DateTime.Now,\r\n\t\t\t\t\t\t");
            
            #line 180 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
;}else if(item.Name=="CreatedDate"){
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t");
            
            #line 181 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
;}else {
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t");
            
            #line 182 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" = data.");
            
            #line 182 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(",\r\n\t\t\t\t\t\t");
            
            #line 183 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
;}}
            
            #line default
            #line hidden
            this.Write("\t\t\t\t},\r\n                data.");
            
            #line 185 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(KeyItems[0].Name));
            
            #line default
            #line hidden
            this.Write("\r\n                );\r\n\t\t\t\tEF.Log.Logger.Trace(EF.Log.TraceLevel.Info, string.Form" +
                    "at(\"更新了表");
            
            #line 187 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write("的数据{0}\",data.");
            
            #line 187 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(KeyItems[0].Name));
            
            #line default
            #line hidden
            this.Write("));\r\n            }\t\r\n\t\t}\r\n\r\n\t\t");
            
            #line 191 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\r\n\t\t");
            
            #line 193 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
 if(KeyItems.Count>1) {
            
            #line default
            #line hidden
            this.Write("\r\n\t\tprivate void DataPortal_Fetch(");
            
            #line 195 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(BusNameSpace));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 195 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(".Criteria info)\r\n        {\r\n            using (var ctx = ContextManager<EFDataCon" +
                    "text>.GetManager(Database.EFramework))\r\n            {\r\n                var i = (" +
                    "from p in ctx.DataContext.");
            
            #line 199 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write("\r\n                         where ");
            
            #line 200 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
 for(int i=0;i<KeyItems.Count;i++){if(i==0){
            
            #line default
            #line hidden
            this.Write("p.");
            
            #line 200 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(KeyItems[i].Name));
            
            #line default
            #line hidden
            this.Write("==info.");
            
            #line 200 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(KeyItems[i].Name));
            
            #line default
            #line hidden
            
            #line 200 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
}else{
            
            #line default
            #line hidden
            this.Write("&&p.");
            
            #line 200 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(KeyItems[i].Name));
            
            #line default
            #line hidden
            this.Write("==info.");
            
            #line 200 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(KeyItems[i].Name));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t\t\t ");
            
            #line 201 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
}}
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\tselect p).SingleOrDefault();\r\n                if (i != null)\r\n              " +
                    "  {\r\n\t\t\t\t\t");
            
            #line 205 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
foreach(var item in Items)
					{
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\tthis.");
            
            #line 207 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" = i.");
            
            #line 207 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t\t  ");
            
            #line 208 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
}
            
            #line default
            #line hidden
            this.Write("\t\t\t\t}\r\n            }\r\n        }\r\n\r\n\t\t[Transactional(TransactionalTypes.Transactio" +
                    "nScope)]\r\n        private void DataPortal_Delete(");
            
            #line 214 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(BusNameSpace));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 214 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(".Criteria info)\r\n        {\r\n            using (var ctx = ContextManager<EFDataCon" +
                    "text>.GetManager(Database.EFramework))\r\n            {\r\n                using (By" +
                    "passPropertyChecks)\r\n                {\r\n                    ctx.DataContext.Dele" +
                    "teByPK<");
            
            #line 220 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write(">(new \r\n\t\t\t\t\t{\r\n\t\t\t\t\t\t");
            
            #line 222 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
 foreach(var item in KeyItems)
						{
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t");
            
            #line 224 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" = info.");
            
            #line 224 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(",\r\n\t\t\t\t\t\t");
            
            #line 225 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
}
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t});\r\n                }\r\n\t\t\t\tEF.Log.Logger.Trace(EF.Log.TraceLevel.Info, stri" +
                    "ng.Format(\"删除了表");
            
            #line 228 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write("的数据");
            
            #line 228 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
for(int i=0;i<KeyItems.Count;i++){
            
            #line default
            #line hidden
            
            #line 228 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(KeyItems[i].Name));
            
            #line default
            #line hidden
            this.Write("={");
            
            #line 228 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write("};");
            
            #line 228 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
;}
            
            #line default
            #line hidden
            this.Write("\"");
            
            #line 228 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
for(int i=0;i<KeyItems.Count;i++){
            
            #line default
            #line hidden
            this.Write(",info.");
            
            #line 228 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(KeyItems[i].Name));
            
            #line default
            #line hidden
            
            #line 228 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
;}
            
            #line default
            #line hidden
            this.Write(@"));
            }
        }

		[Transactional(TransactionalTypes.TransactionScope)]
        private void Child_DeleteSelf()
        {
            using (var ctx = ContextManager<EFDataContext>.GetManager(Database.EFramework))
            {
                using (BypassPropertyChecks)
                {
                    ctx.DataContext.DeleteByPK<");
            
            #line 239 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write(">(new {");
            
            #line 239 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(KeyItems[0].Name));
            
            #line default
            #line hidden
            this.Write("=this.");
            
            #line 239 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(KeyItems[0].Name));
            
            #line default
            #line hidden
            
            #line 239 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
for(int i=1;i<KeyItems.Count;i++){
            
            #line default
            #line hidden
            this.Write(",");
            
            #line 239 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(KeyItems[i].Name));
            
            #line default
            #line hidden
            this.Write("=this.");
            
            #line 239 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(KeyItems[i].Name));
            
            #line default
            #line hidden
            
            #line 239 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
;}
            
            #line default
            #line hidden
            this.Write("});\r\n                }\r\n            }\r\n            EF.Log.Logger.Trace(EF.Log.Tra" +
                    "ceLevel.Info, string.Format(\"删除了表");
            
            #line 242 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write("的数据");
            
            #line 242 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
for(int i=0;i<KeyItems.Count;i++){
            
            #line default
            #line hidden
            
            #line 242 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(KeyItems[i].Name));
            
            #line default
            #line hidden
            this.Write("={");
            
            #line 242 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write("};");
            
            #line 242 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
;}
            
            #line default
            #line hidden
            this.Write("\"");
            
            #line 242 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
for(int i=0;i<KeyItems.Count;i++){
            
            #line default
            #line hidden
            this.Write(",this.");
            
            #line 242 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(KeyItems[i].Name));
            
            #line default
            #line hidden
            
            #line 242 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
;}
            
            #line default
            #line hidden
            this.Write(@"));
        }


		[Transactional(TransactionalTypes.TransactionScope)]
        protected override void DataPortal_Update()
        {
            using (var ctx = ContextManager<EFDataContext>.GetManager(Database.EFramework))
            {
                ");
            
            #line 251 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(BusNameSpace));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 251 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(" data = this;\r\n                ctx.DataContext.UpdateByPK<");
            
            #line 252 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write(">(p => new ");
            
            #line 252 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write("\r\n                {\r\n\t\t\t\t\t\t");
            
            #line 254 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
 foreach(var item in NoKeyItems){  if(item.Name=="ChangedUser"){
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t");
            
            #line 255 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("=ApplicationContext.User.Identity.Name,\r\n\t\t\t\t\t\t");
            
            #line 256 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
;}else if(item.Name=="CreatedUser"){
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t");
            
            #line 257 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
;}else if(item.Name=="ChangedDate"){
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t");
            
            #line 258 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("=System.DateTime.Now,\r\n\t\t\t\t\t\t");
            
            #line 259 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
;}else if(item.Name=="CreatedDate"){
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t");
            
            #line 260 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
;}else {
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t");
            
            #line 261 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" = data.");
            
            #line 261 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(",\r\n\t\t\t\t\t\t");
            
            #line 262 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
;}}
            
            #line default
            #line hidden
            this.Write("\t\t\t\t},new {\r\n\t\t\t\t");
            
            #line 264 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
 foreach(var item in KeyItems)
				{ 
            
            #line default
            #line hidden
            this.Write("                ");
            
            #line 266 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("=data.");
            
            #line 266 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(",\r\n\t\t\t\t");
            
            #line 267 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
}
            
            #line default
            #line hidden
            this.Write("\t\t\t\t});\r\n\t\t\t\tEF.Log.Logger.Trace(EF.Log.TraceLevel.Info, string.Format(\"更新了表");
            
            #line 269 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write("的数据");
            
            #line 269 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
for(int i=0;i<KeyItems.Count;i++){
            
            #line default
            #line hidden
            
            #line 269 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(KeyItems[i].Name));
            
            #line default
            #line hidden
            this.Write("={");
            
            #line 269 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write("};");
            
            #line 269 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
;}
            
            #line default
            #line hidden
            this.Write("\"");
            
            #line 269 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
for(int i=0;i<KeyItems.Count;i++){
            
            #line default
            #line hidden
            this.Write(",this.");
            
            #line 269 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(KeyItems[i].Name));
            
            #line default
            #line hidden
            
            #line 269 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
;}
            
            #line default
            #line hidden
            this.Write("));\r\n            }\r\n        }\r\n\r\n\t\t[Transactional(TransactionalTypes.TransactionS" +
                    "cope)]\r\n        private void Child_Update()\r\n\t\t{\r\n\t\t\tusing (var ctx = ContextMan" +
                    "ager<EFDataContext>.GetManager(Database.EFramework))\r\n            {\r\n           " +
                    "     ");
            
            #line 278 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(BusNameSpace));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 278 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(" data = this;\r\n                ctx.DataContext.UpdateByPK<");
            
            #line 279 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write(">(p => new ");
            
            #line 279 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write("\r\n                {\r\n\t\t\t\t\t\t");
            
            #line 281 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
 foreach(var item in NoKeyItems){  if(item.Name=="ChangedUser"){
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t");
            
            #line 282 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("=ApplicationContext.User.Identity.Name,\r\n\t\t\t\t\t\t");
            
            #line 283 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
;}else if(item.Name=="CreatedUser"){
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t");
            
            #line 284 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
;}else if(item.Name=="ChangedDate"){
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t");
            
            #line 285 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("=System.DateTime.Now,\r\n\t\t\t\t\t\t");
            
            #line 286 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
;}else if(item.Name=="CreatedDate"){
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t");
            
            #line 287 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
;}else {
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t");
            
            #line 288 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" = data.");
            
            #line 288 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(",\r\n\t\t\t\t\t\t");
            
            #line 289 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
;}}
            
            #line default
            #line hidden
            this.Write("\t\t\t\t},new {\r\n\t\t\t\t");
            
            #line 291 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
 foreach(var item in KeyItems)
				{ 
            
            #line default
            #line hidden
            this.Write("                ");
            
            #line 293 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("=data.");
            
            #line 293 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(",\r\n\t\t\t\t");
            
            #line 294 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
}
            
            #line default
            #line hidden
            this.Write("\t\t\t\t});\r\n\t\t\t\tEF.Log.Logger.Trace(EF.Log.TraceLevel.Info, string.Format(\"更新了表");
            
            #line 296 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write("的数据");
            
            #line 296 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
for(int i=0;i<KeyItems.Count;i++){
            
            #line default
            #line hidden
            
            #line 296 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(KeyItems[i].Name));
            
            #line default
            #line hidden
            this.Write("={");
            
            #line 296 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write("};");
            
            #line 296 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
;}
            
            #line default
            #line hidden
            this.Write("\"");
            
            #line 296 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
for(int i=0;i<KeyItems.Count;i++){
            
            #line default
            #line hidden
            this.Write(",this.");
            
            #line 296 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(KeyItems[i].Name));
            
            #line default
            #line hidden
            
            #line 296 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
;}
            
            #line default
            #line hidden
            this.Write("));\r\n            }\r\n\t\t}\r\n\r\n\t\t");
            
            #line 300 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\r\n\t}\r\n\r\n\r\n\tpublic class ");
            
            #line 306 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("Factory:");
            
            #line 306 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(BusNameSpace));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 306 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("\r\n    {\r\n        public static ");
            
            #line 308 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(BusNameSpace));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 308 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(" Fetch(");
            
            #line 308 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write(" data)\r\n        {\r\n            ");
            
            #line 310 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(BusNameSpace));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 310 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(" item = (");
            
            #line 310 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(BusNameSpace));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 310 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(")Activator.CreateInstance(typeof(");
            
            #line 310 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(BusNameSpace));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 310 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("));\r\n            //using (ObjectFactory.BypassPropertyChecks(item))\r\n            " +
                    "{\r\n\t\t\t\t");
            
            #line 313 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
foreach(var item in Items)
				{
            
            #line default
            #line hidden
            this.Write("                item.");
            
            #line 315 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" = data.");
            
            #line 315 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t\t");
            
            #line 316 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
}
            
            #line default
            #line hidden
            this.Write("\t\t\t}\r\n\t\t\tObjectFactory.MarkAsChild(item);\r\n            ObjectFactory.MarkOld(item" +
                    ");\r\n            return item;\r\n        }\r\n\r\n\t\tprivate void DataPortal_Fetch(");
            
            #line 323 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(BusNameSpace));
            
            #line default
            #line hidden
            this.Write(".LambdaExpression lambda)\r\n        {\r\n            using (var ctx = ContextManager" +
                    "<EFDataContext>.GetManager(Database.EFramework))\r\n            {\r\n\t\t\t\tvar exp = l" +
                    "ambda.Resolve<");
            
            #line 327 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write(">();\r\n                var i = (from p in ctx.DataContext.");
            
            #line 328 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write(".Where(exp)\r\n                         select p).FirstOrDefault();\r\n              " +
                    "  if (i != null)\r\n                {\r\n\t\t\t\t\t");
            
            #line 332 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
foreach(var item in Items)
					{
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\tthis.");
            
            #line 334 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" = i.");
            
            #line 334 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t\t\t");
            
            #line 335 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
}
            
            #line default
            #line hidden
            this.Write("}\r\n            }\r\n        }\r\n\t}\r\n\r\n\tpublic class ");
            
            #line 340 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("sFactory : ");
            
            #line 340 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(BusNameSpace));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 340 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("s\r\n    {\r\n        private void DataPortal_Fetch()\r\n        {\r\n            using (" +
                    "var ctx = ContextManager<EFDataContext>.GetManager(Database.EFramework))\r\n      " +
                    "      {\r\n                var i = from p in ctx.DataContext.");
            
            #line 346 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write("\r\n                        select ");
            
            #line 347 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(@"Factory.Fetch(p);
                this.RaiseListChangedEvents = false;
                this.AddRange(i);
                this.RaiseListChangedEvents = true;
            }
        }

		private void DataPortal_Fetch(Paging page)
        {
            using (var ctx = ContextManager<EFDataContext>.GetManager(Database.EFramework))
            {
                var i = (from p in ctx.DataContext.");
            
            #line 358 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write("\r\n                        select ");
            
            #line 359 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(@"Factory.Fetch(p)).Skip(page.StartIndex).Take(page.RowCount);
                this.RaiseListChangedEvents = false;
                this.AddRange(i);
                this.RaiseListChangedEvents = true;
            }
        }

        private void DataPortal_Fetch(PagigExpress page)
        {
            using (var ctx = ContextManager<EFDataContext>.GetManager(Database.EFramework))
            {
                var exp = page.Lambda.Resolve<");
            
            #line 370 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write(">();\r\n                var i = (from p in ctx.DataContext.");
            
            #line 371 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write(".Where(exp)\r\n                         select ");
            
            #line 372 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(@"Factory.Fetch(p)).Skip(page.StartIndex).Take(page.RowCount);
                this.RaiseListChangedEvents = false;
                this.AddRange(i);
                this.RaiseListChangedEvents = true;
            }
        }

		[Transactional(TransactionalTypes.TransactionScope)]
        private void DataPortal_Update()
        {
            this.Child_Update();
        }

    }

	public class ");
            
            #line 387 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("sFactory : ");
            
            #line 387 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(BusNameSpace));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 387 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("s\r\n    {\r\n        private void DataPortal_Fetch()\r\n        {\r\n            using (" +
                    "var ctx = ContextManager<EFDataContext>.GetManager(Database.EFramework))\r\n      " +
                    "      {\r\n                var i = from p in ctx.DataContext.");
            
            #line 393 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write("\r\n                        select ");
            
            #line 394 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(@"Factory.Fetch(p);
                this.RaiseListChangedEvents = false;
                this.AddRange(i);
                this.RaiseListChangedEvents = true;
            }
        }

		private void DataPortal_Fetch(Paging page)
        {
            using (var ctx = ContextManager<EFDataContext>.GetManager(Database.EFramework))
            {
                var i = (from p in ctx.DataContext.");
            
            #line 405 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write("\r\n                        select ");
            
            #line 406 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(@"Factory.Fetch(p)).Skip(page.StartIndex).Take(page.RowCount);
                this.RaiseListChangedEvents = false;
                this.AddRange(i);
                this.RaiseListChangedEvents = true;
            }
        }

        private void DataPortal_Fetch(PagigExpress page)
        {
            using (var ctx = ContextManager<EFDataContext>.GetManager(Database.EFramework))
            {
                var exp = page.Lambda.Resolve<");
            
            #line 417 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write(">();\r\n                var i = (from p in ctx.DataContext.");
            
            #line 418 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableName));
            
            #line default
            #line hidden
            this.Write(".Where(exp)\r\n                         select ");
            
            #line 419 "E:\MyText\ClassLibrary1\MyCodeAddin\EditRead\EditReadObjectFactory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(@"Factory.Fetch(p)).Skip(page.StartIndex).Take(page.RowCount);
                this.RaiseListChangedEvents = false;
                this.AddRange(i);
                this.RaiseListChangedEvents = true;
            }
        }

		[Transactional(TransactionalTypes.TransactionScope)]
        private void DataPortal_Update()
        {
            this.Child_Update();
        }

    }
}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "11.0.0.0")]
    public class EditReadObjectFactoryBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
